services:
  gateway-server:
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    container_name: gateway-server
    ports:
      - "3000:3000"
    environment:
      - PORT=${GATEWAY_SERVER_PORT}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - microservice-network

  auth-server:
    build:
      context: ./auth-server
      dockerfile: Dockerfile
    container_name: auth-server
    ports:
      - "3001:3001"
    environment:
      - PORT=${AUTH_SERVER_PORT}
      - JWT_SECRET=${JWT_SECRET}
      - MONGODB_URI=${AUTH_MONGODB_URI}
    networks:
      - microservice-network

  auth-database:
    image: mongo:latest
    container_name: auth-database
    ports:
      - "27017:27017"
    volumes:
      - auth-database:/data/db
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge

volumes:
  auth-database:
