version: '3.8'

services:
  gateway-server:
    build:
      context: ./gateway-server
      dockerfile: Dockerfile
    container_name: gateway-server
    ports:
      - "3000:3000"
    environment:
      - PORT=${PORT}
      - JWT_SECRET=${JWT_SECRET}
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge


